# Generated by Django 4.2.16 on 2024-11-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='prise',
            field=models.FloatField(default=0, null=True, verbose_name='Цена'),
        ),
    ]
